groups:
- name: backup
  jobs:
    - export-om-installation
    - bbr-backup-ert
    - bbr-backup-director
- name: unlock
  jobs:
    - bbr-director-unlock
    - bbr-ert-unlock

jobs:
- name: lock-deployment
  serial: true
  plan:
  - put: lock
    params: {claim: lock}
  - get: scheduler
    trigger: true
    ensure:
      put: lock
      params:
        release: lock

- name: export-om-installation
  plan:
  - aggregate:
    - get: lock
      trigger: true
      passed: [lock-deployment]
    - get: bbr-pipeline-tasks-repo
  - task: export-om-installation
    file: bbr-pipeline-tasks-repo/tasks/export-om-installation/task.yml
    params:
      SKIP_SSL_VALIDATION: {{skip-ssl-validation}}
      OPSMAN_URL: {{opsman-url}}
      OPSMAN_USERNAME: {{opsman-username}}
      OPSMAN_PASSWORD: {{opsman-password}}
  - put: om-backup-artifact
    params:
      file: om-installation/installation.zip

- name: bbr-backup-ert
  plan:
  - aggregate:
    - get: lock
      trigger: true
      passed: [lock-deployment]
    - get: bbr-pipeline-tasks-repo
    - get: bbr-release
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-binary/task.yml
  - task: bbr-backup-ert
    file: bbr-pipeline-tasks-repo/tasks/bbr-backup-ert/task.yml
    params:
      SKIP_SSL_VALIDATION: {{skip-ssl-validation}}
      OPSMAN_URL: {{opsman-url}}
      OPSMAN_USERNAME: {{opsman-username}}
      OPSMAN_PASSWORD: {{opsman-password}}
  - put: ert-backup-bucket
    params:
      file: ert-backup-artifact/ert-backup.tar

- name: bbr-backup-director
  plan:
  - aggregate:
    - get: lock
      trigger: true
      passed: [lock-deployment]
    - get: bbr-pipeline-tasks-repo
    - get: bbr-release
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-binary/task.yml
  - task: bbr-backup-director
    file: bbr-pipeline-tasks-repo/tasks/bbr-backup-director/task.yml
    params:
      SKIP_SSL_VALIDATION: {{skip-ssl-validation}}
      OPSMAN_URL: {{opsman-url}}
      OPSMAN_USERNAME: {{opsman-username}}
      OPSMAN_PASSWORD: {{opsman-password}}
  - put: director-backup-bucket
    params:
      file: director-backup-artifact/director-backup.tar

- name: unlock-deployment
  plan:
  - get: lock
    trigger: true
    passed: [export-om-installation, bbr-backup-ert, bbr-backup-director]
  - put: lock
    params:
      release: lock

- name: bbr-ert-unlock
  serial: true
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-repo
      trigger: false
    - get: bbr-release
      trigger: false
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-binary/task.yml
  - task: bbr-ert-unlock
    file: bbr-pipeline-tasks-repo/tasks/bbr-ert-unlock/task.yml
    params:
      SKIP_SSL_VALIDATION: {{skip-ssl-validation}}
      OPSMAN_URL: {{opsman-url}}
      OPSMAN_USERNAME: {{opsman-username}}
      OPSMAN_PASSWORD: {{opsman-password}}

- name: bbr-director-unlock
  serial: true
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-repo
      trigger: false
    - get: bbr-release
      trigger: false
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-binary/task.yml
  - task: bbr-director-unlock
    file: bbr-pipeline-tasks-repo/tasks/bbr-director-unlock/task.yml
    params:
      SKIP_SSL_VALIDATION: {{skip-ssl-validation}}
      OPSMAN_URL: {{opsman-url}}
      OPSMAN_USERNAME: {{opsman-username}}
      OPSMAN_PASSWORD: {{opsman-password}}

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: bbr-pipeline-tasks-repo
  type: git
  source:
    uri: https://github.com/aaa-ncnu-ie/bbr-pcf-pipeline-tasks.git
    branch: master
- name: om-backup-artifact
  type: s3
  source:
    bucket: {{backup-artifact-bucket}}
    region_name: {{storage-region}}
    endpoint: {{storage-endpoint}}
    access_key_id: {{storage-access-key-id}}
    secret_access_key: {{storage-secret-access-key}}
    versioned_file: installation.zip
- name: ert-backup-bucket
  type: s3
  source:
    bucket: {{backup-artifact-bucket}}
    region_name: {{storage-region}}
    endpoint: {{storage-endpoint}}
    access_key_id: {{storage-access-key-id}}
    secret_access_key: {{storage-secret-access-key}}
    versioned_file: ert-backup.tar
- name: director-backup-bucket
  type: s3
  source:
    bucket: {{backup-artifact-bucket}}
    region_name: {{storage-region}}
    endpoint: {{storage-endpoint}}
    access_key_id: {{storage-access-key-id}}
    secret_access_key: {{storage-secret-access-key}}
    versioned_file: director-backup.tar
- name: bbr-release
  type: pivnet
  source:
    api_token: {{pivnet-api-token}}
    product_slug: p-bosh-backup-and-restore
- name: scheduler
  type: time
  source:
    start: {{scheduler-time-window-start}}
    stop: {{scheduler-time-window-stop}}
    location: {{scheduler-time-location}}
- name: lock
  type: pool
  source:
    uri: {{lock-git-repo-uri}}
    branch: {{lock-git-repo-branch}}
    pool: {{lock-pool-name}}
    private_key: {{lock-git-private-key}}
