platform: linux
image_resource:
  type: docker-image
  source: {repository: ubuntu}

inputs:
  - { name: bbr-pipeline-tasks-repo }
run:
  path: bbr-pipeline-tasks-repo/tasks/deadmansnitch/push-zapier.sh
