---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: docker.prod.pdc.digital.csaa-insurance.aaa.com/bbr-pipeline
    tag: latest

inputs:
  - name: bbr-pipeline-tasks-repo

outputs:
  - name: s3-upload

params:
  storage-access-key-id:
  storage-secret-access-key:
  backup-artifact-bucket:
  backup_file_name:

run:
  path: bbr-pipeline-tasks-repo/tasks/s3-upload/task.rb
